allowBuilds:
  '@vscode/vsce-sign': false
  esbuild: true
  keytar: false
engineStrict: true
minimumReleaseAge: 1440
minimumReleaseAgeStrict: true
preferSymlinkedExecutables: true
saveExact: true
strictDepBuilds: true
